apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: super-meal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: satyamdocker26/super-meal-backend:latest   # update to backend image  
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: backend-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
